trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - name: 'vmImageName'
    value: 'ubuntu-latest'

  - name: 'System.Debug'
    value: 'false'

  - name: StageName
    value: 'LaTeX_Build_Ubuntu_Latest'

  - name: LatexFileName
    value: 'LatexRussianTemplate'

  - name: LatexFilePath
    value: '$(System.DefaultWorkingDirectory)/src/$(LatexFileName).tex'

  - name: OutputDirectory
    value: '$(System.DefaultWorkingDirectory)/out'

stages:
  - stage: ${{ variables.StageName }}
    displayName: ${{ variables.StageName }}
    jobs:
      - job: ${{ variables.StageName }}
        displayName: ${{ variables.StageName }}
        pool:
          vmImage: ${{ variables.vmImageName }}

        steps:
          - checkout: self
            fetchDepth: 0

          - task: gitversion/setup@3
            displayName: 'GitVersion Setup'
            inputs:
              versionSpec: '5.x'

          - task: gitversion/execute@3
            displayName: 'GitVersion Execute'

          - bash: echo $Action$BuildVersion
            displayName: 'Set Build Version'
            env:
              Action: '##vso[build.updatebuildnumber]'
              BuildVersion: '$(GitVersion.SemVer)'

          - bash: |
              sudo apt-get install texlive-latex-extra
              sudo apt-get install texlive-lang-cyrillic
            displayName: 'Install TeXLive'

          - bash: |
              sudo mkdir -p $(OutputDirectory)
              sudo chmod -R 775 $(OutputDirectory)
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            displayName: 'Create Output Directory'

          - bash: |
              newVersion="$(GitVersion.SemVer)+$(GitVersion.BranchName).$(GitVersion.ShortSha)"
              sed -i "s|Local-0.1.0|$newVersion|" "src/sections/version.tex"
            displayName: 'Update version.tex'
            workingDirectory: '$(System.DefaultWorkingDirectory)'

          - bash: |
              sudo fmtutil-sys --all
            displayName: 'Update TeXLive Formats'

          - bash: |
              echo "Compiling LaTeX document first time ..."
              pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf \
                -output-directory=$(OutputDirectory) \
                -aux-directory=$(OutputDirectory) $(LatexFileName).tex
              echo "Compiling LaTeX document second time ..."
              pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf \
                -output-directory=$(OutputDirectory) \
                -aux-directory=$(OutputDirectory) $(LatexFileName).tex
            workingDirectory: '$(System.DefaultWorkingDirectory)/src'
            displayName: 'Build Document'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(OutputDirectory)'
              artifact: '$(LatexFileName)_$(GitVersion.SemVer)'
              publishLocation: 'pipeline'
